# Generated by Django 4.1.1 on 2022-10-14 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InterfaceApp', '0002_alter_performancelist_enddate_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PerformanceList',
        ),
    ]
