# Generated by Django 4.1.1 on 2022-10-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('InterfaceApp', '0003_delete_performancelist'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceDB',
            fields=[
                ('seq', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('place', models.CharField(max_length=50)),
                ('realmName', models.CharField(max_length=10)),
                ('area', models.CharField(max_length=10, null=True)),
                ('thumbnail', models.BinaryField()),
                ('gpsX', models.FloatField(null=True)),
                ('gpsY', models.FloatField(null=True)),
            ],
        ),
    ]
