# Generated by Django 4.1.1 on 2022-10-17 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('InterfaceApp', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishlistDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance_seq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InterfaceApp.performancedb')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
